#!/bin/bash

# ./run karaoke_player /usr/share/soundfonts/FluidR3_GM.sf2 /home/httpd/html/LinuxSound/Karaoke/JavaSound/java/nightsin.kar

PATH=fluidsynth-1.1.6/src:$PATH
export LD_LIBRARY_PATH=./fluidsynth-1.1.6/src/.libs/
eval $*
